version: '2'
services:
    acspedia-app:
        image: acspedia
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://acspedia-postgresql:5432/ACSPedia
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    acspedia-postgresql:
        extends:
            file: postgresql.yml
            service: acspedia-postgresql
